(*top* (*pi* xml "version=\'1.0\' encoding=\'ISO-8859-1\'")
       (rss (@ (version "2.0"))
            (channel (title "okmij.org")
                     (description "okmij.org")
                     (language "en-us")
                     (ttl "21600")
                     (generator "HSXML->RSS")
                     (pubDate "1 Mar 2008 12:00:00 GMT")
                     (link "http://okmij.org/ftp/README.html")
                     (http://www.w3.org/2005/Atom:link (@ (type "application/rss+xml")
                                                          (rel "self")
                                                          (href "http://okmij.org/ftp/rss.xml")))
                     (item (description "Type(class)-directed symbolic differentiation")
                           (link "http://okmij.org/ftp/Computation/Generative.html#diff-typeclass")
                           (guid "http://okmij.org/ftp/Computation/Generative.html#diff-typeclass")
                           (pubDate "1 Mar 2008 12:00:00 GMT"))
                     (item (description "Most optimal symbolic differentiation of compiled numeric functions")
                           (link "http://okmij.org/ftp/Computation/Generative.html#diff-th")
                           (guid "http://okmij.org/ftp/Computation/Generative.html#diff-th")
                           (pubDate "1 Mar 2008 12:00:00 GMT"))
                     (item (description "Do-notation for restricted monads: <code>Data.Set</code> as <code>MonadPlus</code>")
                           (link "http://okmij.org/ftp/Haskell/types.html#restricted-datatypes")
                           (guid "http://okmij.org/ftp/Haskell/types.html#restricted-datatypes")
                           (pubDate "1 Mar 2008 12:00:00 GMT"))
                     (item (description "Total stream processors and their applications to all infinite streams\
<br>\
Response to `Seemingly impossible functional programs\'")
                           (link "http://okmij.org/ftp/Algorithms.html#total-sp")
                           (guid "http://okmij.org/ftp/Algorithms.html#total-sp")
                           (pubDate "1 Feb 2008 12:00:00 GMT"))
                     (item (description "Closing the Stage: from staged code to typed closures")
                           (link "http://okmij.org/ftp/Computation/Generative.html#metafx")
                           (guid "http://okmij.org/ftp/Computation/Generative.html#metafx")
                           (pubDate "1 Feb 2008 12:00:00 GMT"))
                     (item (description "Variable (type)state `monad\'")
                           (link "http://okmij.org/ftp/Computation/monads.html#param-monad")
                           (guid "http://okmij.org/ftp/Computation/monads.html#param-monad")
                           (pubDate "1 Feb 2008 12:00:00 GMT"))
                     (item (description "Finally Tagless, Partially Evaluated: Tagless Staged Interpreters for Simpler Typed Languages\
<br>\
on a new web page on typed tagless interpretations, typechecking, staging, and dependent types")
                           (link "http://okmij.org/ftp/Computation/tagless-typed.html#tagless-final")
                           (guid "http://okmij.org/ftp/Computation/tagless-typed.html#tagless-final")
                           (pubDate "1 Jan 2008 12:00:00 GMT"))
                     (item (description "Typed Compilation")
                           (link "http://okmij.org/ftp/Computation/tagless-typed.html#typed-compilation")
                           (guid "http://okmij.org/ftp/Computation/tagless-typed.html#typed-compilation")
                           (pubDate "1 Jan 2008 12:00:00 GMT"))
                     (item (description "Tagless (staged) interpreter typeclass for typed languages")
                           (link "http://okmij.org/ftp/Computation/tagless-typed.html#tagless-Eval")
                           (guid "http://okmij.org/ftp/Computation/tagless-typed.html#tagless-Eval")
                           (pubDate "1 Jan 2008 12:00:00 GMT"))
                     (item (description "Typed compilation to HOAS as emulation of staging")
                           (link "http://okmij.org/ftp/Computation/tagless-typed.html#tc-final")
                           (guid "http://okmij.org/ftp/Computation/tagless-typed.html#tc-final")
                           (pubDate "1 Jan 2008 12:00:00 GMT"))
                     (item (description "Metatypechecking: Staged Typed Compilation into GADT via typeclasses")
                           (link "http://okmij.org/ftp/Computation/tagless-typed.html#tc-GADT-tc")
                           (guid "http://okmij.org/ftp/Computation/tagless-typed.html#tc-GADT-tc")
                           (pubDate "1 Jan 2008 12:00:00 GMT"))
                     (item (description "Typed compilation via GADTs")
                           (link "http://okmij.org/ftp/Computation/tagless-typed.html#tc-GADT")
                           (guid "http://okmij.org/ftp/Computation/tagless-typed.html#tc-GADT")
                           (pubDate "1 Jan 2008 12:00:00 GMT"))
                     (item (description "Relating Final and Initial typed tagless representations")
                           (link "http://okmij.org/ftp/Computation/tagless-typed.html#in-fin")
                           (guid "http://okmij.org/ftp/Computation/tagless-typed.html#in-fin")
                           (pubDate "1 Jan 2008 12:00:00 GMT"))
                     (item (description "A new page on Meta-Theory and Logical Frameworks, with an example of formalizing monadic System F and mechanically proving its type soundness")
                           (link "http://okmij.org/ftp/Computation/meta-theory.html")
                           (guid "http://okmij.org/ftp/Computation/meta-theory.html")
                           (pubDate "7 Dec 2007 12:00:00 GMT"))
                     (item (description "A summary of the J. Strother Moore\'s talk Machine reasoning about machines: ACL2 theorem prover")
                           (link "http://okmij.org/ftp/Computation/my-summaries.html#ACL2")
                           (guid "http://okmij.org/ftp/Computation/my-summaries.html#ACL2")
                           (pubDate "7 Dec 2007 12:00:00 GMT"))
                     (item (description "Fixpoint combinator from typed prompt/control")
                           (link "http://okmij.org/ftp/Computation/Continuations.html#typed-control-fix")
                           (guid "http://okmij.org/ftp/Computation/Continuations.html#typed-control-fix")
                           (pubDate "7 Dec 2007 12:00:00 GMT"))
                     (item (description "General recursive types via delimited continuations")
                           (link "http://okmij.org/ftp/Computation/Continuations.html#delimcc-rectype")
                           (guid "http://okmij.org/ftp/Computation/Continuations.html#delimcc-rectype")
                           (pubDate "7 Dec 2007 12:00:00 GMT"))
                     (item (description "Noted that the paper Lightweight static capabilities has been published in Electr. Notes Theor. Comput. Sci, 174(7), pp. 79-104, 2007")
                           (link "http://okmij.org/ftp/Computation/lightweight-dependent-typing.html#Lightweight")
                           (guid "http://okmij.org/ftp/Computation/lightweight-dependent-typing.html#Lightweight")
                           (pubDate "7 Dec 2007 12:00:00 GMT"))
                     (item (description "A new page Monadic Regions with the description of Simple IO regions, in Haskell98 + existentials")
                           (link "http://okmij.org/ftp/Haskell/regions.html")
                           (guid "http://okmij.org/ftp/Haskell/regions.html")
                           (pubDate "4 Nov 2007 12:00:00 GMT"))
                     (item (description "Local globally-quantified exceptions in OCaml, and their relationship with delimited continuations")
                           (link "http://okmij.org/ftp/ML/ML.html#poly-exn")
                           (guid "http://okmij.org/ftp/ML/ML.html#poly-exn")
                           (pubDate "4 Nov 2007 12:00:00 GMT"))
                     (item (description "Newer FastCGI and the memory-efficient IO interface")
                           (link "http://okmij.org/ftp/Haskell/misc.html#NewerCGI")
                           (guid "http://okmij.org/ftp/Haskell/misc.html#NewerCGI")
                           (pubDate "4 Nov 2007 12:00:00 GMT"))
                     (item (description "Self-quoting fix-points: Quines, in Scheme and MetaOCaml")
                           (link "http://conway.rutgers.edu/~ccshan/wiki/blog/posts/Quines/")
                           (guid "http://conway.rutgers.edu/~ccshan/wiki/blog/posts/Quines/")
                           (pubDate "4 Nov 2007 12:00:00 GMT"))
                     (item (description "Generic de-serialization")
                           (link "http://okmij.org/ftp/Haskell/generics.html#de-serialization")
                           (guid "http://okmij.org/ftp/Haskell/generics.html#de-serialization")
                           (pubDate "5 Oct 2007 12:00:00 GMT"))
                     (item (description "In quest for staged calculus")
                           (link "http://okmij.org/ftp/Computation/Generative.html#staged-calculi")
                           (guid "http://okmij.org/ftp/Computation/Generative.html#staged-calculi")
                           (pubDate "5 Oct 2007 12:00:00 GMT"))
                     (item (description "Dependent open terms and the evaluation contexts that bind them")
                           (link "http://okmij.org/ftp/Computation/Generative.html#dependent-open-binding")
                           (guid "http://okmij.org/ftp/Computation/Generative.html#dependent-open-binding")
                           (pubDate "5 Oct 2007 12:00:00 GMT"))
                     (item (description "Delimited continuations in operating systems")
                           (link "http://okmij.org/ftp/Computation/Continuations.html#context-OS")
                           (guid "http://okmij.org/ftp/Computation/Continuations.html#context-OS")
                           (pubDate "1 Sep 2007 12:00:00 GMT"))
                     (item (description "State Monad as a term algebra")
                           (link "http://okmij.org/ftp/Haskell/types.html#state-algebra")
                           (guid "http://okmij.org/ftp/Haskell/types.html#state-algebra")
                           (pubDate "1 Sep 2007 12:00:00 GMT"))
                     (item (description "Type checking as small-step abstract evaluation")
                           (link "http://okmij.org/ftp/Computation/Computation.html#small-step-typechecking")
                           (guid "http://okmij.org/ftp/Computation/Computation.html#small-step-typechecking")
                           (pubDate "1 Aug 2007 12:00:00 GMT"))
                     (item (description "A Substructural Type System for Delimited Continuations")
                           (link "http://okmij.org/ftp/Computation/Continuations.html#delimcc-type")
                           (guid "http://okmij.org/ftp/Computation/Continuations.html#delimcc-type")
                           (pubDate "1 Aug 2007 12:00:00 GMT"))
                     (item (description "Smash along your boilerplate  -- an approach to generic programming in Haskell")
                           (link "http://okmij.org/ftp/Haskell/generics.html#Smash")
                           (guid "http://okmij.org/ftp/Haskell/generics.html#Smash")
                           (pubDate "1 Aug 2007 12:00:00 GMT"))
                     (item (description "Generic traversal of non-existent terms")
                           (link "http://okmij.org/ftp/Haskell/generics.html#unreal-traverse")
                           (guid "http://okmij.org/ftp/Haskell/generics.html#unreal-traverse")
                           (pubDate "1 Aug 2007 12:00:00 GMT"))
                     (item (description "<code>Typeable</code> makes Haskell98 unsound")
                           (link "http://okmij.org/ftp/Haskell/types.html#unsound-typeable")
                           (guid "http://okmij.org/ftp/Haskell/types.html#unsound-typeable")
                           (pubDate "1 Aug 2007 12:00:00 GMT")))))
